### ISSUE TITLE
How is that possible that proof is the same hash as h ?

### ISSUE THREAD

**Issue by fonzarely** [mattdf/payment-channel#1]
I dont understand how that code:
`
  proof = sha3(this, value);
  if (proof != h) throw;
`
which seems to be equivalent to: 
`sha3(ContractAddress, value) == sha3(RadomAddress, value)`
may works.

Could you add a unit test that call contract's `CloseChannel` function ?

**Comment by mattdf** [comment]
Don't know where you're getting `sha3(RandomAddress, ...)` from. 

A signature would be generated as follows:

```
hash = web3.sha3(ContractAddress, value)
signature = eth.sign(AccountAddress, hash)
```

`eth.sign` returns a `signature` string that can be decomposed into `v, r, s` variables.

You would then call the contract like: 

`CloseChannel(hash, v, r, s, value)`

Nowhere in the contract does it ever hash a random value. In the code, `sha3(this, value)`, `this` is the current contract's address.

**Comment by fonzarely** [comment]
Yes I see that,
When I test the contract the line `if (proof != h) throw;` throws.
I'll try to generate a signature following your example.

I provided RandomAddress as an example only.

Thanks
