### ISSUE TITLE
How can the recipient know the contract is valid?

### ISSUE THREAD

**Issue by erikdubbelboer** [mattdf/payment-channel#2]
How can the recipient know the contract is valid and not just a decoy contract that also expose the same methods but never pays out?

**Comment by erikdubbelboer** [comment]
Would the recipient have to compile the contract code himself to compare the bytecode to the one being used in the transaction?

**Comment by mattdf** [comment]
Just compare the hash of the bytecode? Or rewrite the contract such that it doesn't need to be redeployed to be used.

**Comment by erikdubbelboer** [comment]
Ok thank you, just wanted to make sure I'm not missing something obvious.
