### ISSUE TITLE
Named variables?

### ISSUE THREAD

**Issue by julien51** [mattdf/payment-channel#5]
Hi!
I think your example is one of the clearest... Yet, it would be helpful if you used more descriptive variable names in the method signature ;)

**Comment by ppoliani** [comment]
There is currently an open issue regarding the documentation of `ecrecover` function. https://github.com/ethereum/solidity/issues/681

However, you can look into the `web3` [docs](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethsign) for more details. 

I can try to explain how it works: 

Bob signs a hash of (contract_address, value): this can be done using the `web3` helper function:

```
const h = web3.sha3(`${contract_address}${value}`);
const sig = web3.eth.sign(address, h);
```

Alice will get the `sig` and when she wants to close the channel she can send a transaction that will call the `CloseChannel` function of the smart contract. But she must first pass all the required parameters. That's actually quite simple if you have the `sig`:

```
 const r = `0x${sig.slice(0, 64)}`
 const s = `0x${sig.slice(64, 128)}`
 const v = web3.toDecimal(sig.slice(128, 130)) + 27
```

Then the smart contract can use `ecrecover` which as stated in the [Solidity docs](http://solidity.readthedocs.io/en/latest/units-and-global-variables.html#mathematical-and-cryptographic-functions):


> ecrecover(bytes32 hash, uint8 v, bytes32 r, bytes32 s) returns (address):
> recover the address associated with the public key from elliptic curve signature or return zero on  error

The parameter names are kind of a convention when using ECDSA values.

**Comment by julien51** [comment]
Thanks a lot! this clarifies things a little bit...
