### ISSUE TITLE
wouldnt this be an || statemenet instead of &&

### ISSUE THREAD

**Issue by oojr** [mattdf/payment-channel#6]
https://github.com/mattdf/payment-channel/blob/515c1b935ac43afc6bf54fcaff68cf8521595b0b/channel.sol#L27

**Comment by erikdubbelboer** [comment]
No the person closing the channel, the signer, needs to be one of those two. If he is both it would mean it was a payment channel to himself.

**Comment by oojr** [comment]
so `signer = ecrecover(h, v, r, s);` returns a signer address if that address is not the channelSender or the channelRecipient the smart contract will throw? So Bob sends Alice money but only Charles can close according to the contract or am I missing something

**Comment by oojr** [comment]
actually I understand Bob can't be channelSender and channelRecipient
